@startuml Container
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(platform, "IoT Monitoring Platform") {
    Container(postgresql_keycloak, "PostgreSQL (Keycloak)", "Реляционная БД", "База данных для Keycloak")
    Container(postgresql_dcs, "PostgreSQL DCS", "Шардированная Реляционная БД", "Шардированная база данных для хранения информации об устройствах")
    Container(redis, "Redis", "In-memory cache", "Кэширование запросов")
    Container(cassandra_cluster, "Cassandra", "NoSQL", "Хранение событий")
    Container(kafka_cluster, "Kafka", "Брокер сообщений", "Топики: event / dlq / device-id")
    Container(minio, "MinIO", "Объектное хранилище", "Хранение артефактов/ошибок (DLQ)")
    Container_Ext(schema_registry, "Schema Registry", "Реестр схем Kafka")
    Container_Ext(kafka_ui, "Kafka UI", "Веб-интерфейс Kafka")
    Container_Ext(nexus, "Nexus", "Артефактный репозиторий", "Репозиторий для хранение артефактов сборки")
    Container(avro_schemas, "Avro Schemas", "Централизованное хранилище Авро схем", "Модуль для хранения всех Avro схем и их версий")
    Boundary(obs, "Observability") {
        Container(alloy, "Alloy", "Агент телеметрии", "Сбор и маршрутизация логов/метрик")
        Container(prometheus, "Prometheus", "TSDB", "Хранение/запрос метрик")
        Container(loki, "Loki", "Логи", "Хранение и поиск логов")
        Container(grafana, "Grafana", "UI", "Визуализация телеметрии")
        Container(tempo, "Tempo", "Трейсинг", "Хранение и поиск трассировок")

        Container(redis_exporter, "Redis Exporter", "Exporter", "Метрики Redis")
        Container(kafka_exporter, "Kafka Exporter", "Exporter", "Метрики Kafka")
        Container(postgres_exporter, "PostgreSQL Exporter", "Exporter", "Метрики PostgreSQL")
        Container(event_collector_service, "Event Collector Service", "Сервис сбора событий", "Сбор событий от устройств")
        Container(device_collector_service, "Device Collector Service", "Сервис сбора информаций об устройствах", "Сбор событий об устройствах")
        Container_Ext(keycloak, "Keycloak", "OAuth2", "Аутентификация и авторизация")
        Container(device_service, "Device Service", "Сервис управления устройствами", "CRUD операции для устройств")
    }
}
Container_Ext(zookeeper, "Zookeeper", "Координация брокеров")


Rel(keycloak, postgresql_keycloak, "Читает/пишет")
Rel(kafka_cluster, zookeeper, "Координация/метаданные")

Rel(redis_exporter, redis, "Collects metrics")
Rel(kafka_exporter, kafka_cluster, "Collects metrics")
Rel(postgres_exporter, postgresql_dcs, "Collects metrics")
Rel(postgres_exporter, postgresql_keycloak, "Collects metrics")

Rel(prometheus, redis_exporter, "Scrapes /metrics")
Rel(prometheus, kafka_exporter, "Scrapes /metrics")
Rel(prometheus, postgres_exporter, "Scrapes /metrics")
Rel(prometheus, event_collector_service, "Scrapes /metrics")
Rel(prometheus, device_collector_service, "Scrapes /metrics")
Rel(prometheus, keycloak, "Scrapes /metrics")
Rel(prometheus, device_service, "Scrapes /metrics")

Rel(grafana, prometheus, "Queries metrics")
Rel(grafana, loki, "Queries logs")

Rel(alloy, loki, "Отправка логов")
Rel(alloy, prometheus, "remote_write (если используется)")
Rel(alloy, tempo, "Отправка трассировок")

Rel(kafka_ui, kafka_cluster, "Просмотр/управление топиками")

Rel(event_collector_service, kafka_cluster, "Запись уникальных устройств в топик device-id")
Rel(kafka_cluster, event_collector_service, "Чтения событий из топика events")
Rel(event_collector_service, cassandra_cluster, "Запись событий")

Rel(device_collector_service, postgresql_dcs, "Write/Update device")
Rel(device_collector_service, schema_registry, "Retrieve/Register Avro schema")
Rel(event_collector_service, schema_registry, "Retrieve/Register Avro schema")

Rel(avro_schemas, nexus, "Publish artifact (jar-file) in Nexus")
Rel(event_collector_service, nexus, "Get Avro schemas artifact (jar-file) from Nexus")
Rel(device_collector_service, nexus, "Get Avro schemas artifact (jar-file) from Nexus")

Rel(device_service, kafka_cluster, "Публикация устройств в топик device-topic")
Rel(device_service, redis, "Кэширование hot данных")

@enduml
